CREATE TABLE Posts (
    Id INT PRIMARY KEY IDENTITY,
    Title NVARCHAR(255) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME NULL,
    UserId INT,
    FOREIGN KEY (UserId) REFERENCES Register(Id)
);
